# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout SuperCollider Code
        uses: actions/checkout@v3
        with:
          repository: supercollider/supercollider
          path: supercollider

      - name: Make build dir
        working-directory: main
        run: mkdir build

      - name: cmake
        working-directory: main/build
        run: |
          cmake \
            -DSC_PATH=../supercollider \
            -DCMAKE_BUILD_TYPE=RELEASE \
            ..
      
      - name: make
        working-directory: main/build
        run: make

      - name: Upload linux build
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: main/build/AbsRatio.so
          
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-linux
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download linux build
        uses: actions/upload-artifact@v3
        with:
          name: build-linux
          path: AbsRatio.so
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: AbsRatio.so
