name: Build & Release

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout SuperCollider Code
        uses: actions/checkout@v3
        with:
          repository: supercollider/supercollider
          path: SuperCollider

      - name: Make build dir
        working-directory: main
        run: mkdir build

      - name: cmake
        working-directory: main/build
        run: |
          cmake \
            -DSC_PATH=../SuperCollider \
            -DCMAKE_BUILD_TYPE=RELEASE \
            ..
      
      - name: make
        working-directory: main/build
        run: make

      - name: Upload .so
        uses: actions/upload-artifact@v3
        with:
          name: build-so
          path: main/build/AbsRatio.so

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout SuperCollider Code
        uses: actions/checkout@v3
        with:
          repository: supercollider/supercollider
          path: SuperCollider

      - name: Make build dir
        working-directory: main
        run: mkdir build

      - name: cmake
        working-directory: main/build
        run: |
          cmake \
            -DSC_PATH=../SuperCollider \
            -DCMAKE_BUILD_TYPE=RELEASE \
            ..
      
      - name: make
        working-directory: main/build
        run: make

      - name: Upload .scx
        uses: actions/upload-artifact@v3
        with:
          name: build-scx
          path: main/build/AbsRatio.scx

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download built .so
        uses: actions/download-artifact@v3
        with:
          name: build-so

      - name: Download built .scx
        uses: actions/download-artifact@v3
        with:
          name: build-scx

      - name: Detect Version from Quark File
        id: version
        working-directory: main
        run: |
          echo "quark-version=$(cat AbsRatio.quark | sed -n "s/^\s*version:\s*\"\(.*\)\"[,?]/\1/p")" >> $GITHUB_OUTPUT

      - name: Release
        uses: EndBug/add-and-commit@v9
        with:
          add: '["*.scx", "*.so"]'
          message: 'Compiled by GitHub Action'
          new_branch: 'release/${{ steps.version.outputs.quark-version }}'
          tag: ${{ steps.version.outputs.quark-version }}
